# Generated by Django 5.1.1 on 2024-09-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('section', models.CharField(max_length=5)),
                ('branch', models.CharField(max_length=100)),
                ('technical_skills', models.CharField(max_length=200)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mobile', models.CharField(max_length=10)),
                ('joining_year', models.IntegerField()),
            ],
        ),
    ]
